export enum encryptedStorageKeys {
  ENCRYPTEDKEY = 'j43kj4234j2k3j424j3k4j1j3423b4rnrebtnbfsdbmfbdmdsfns3bqnm4enasbdbbs',
}

export enum screenNames {
  METERIALBOTTOMNAVIGATOR = 'METERIALBOTTOMNAVIGATOR',
  HOME = 'HOME',
  MYADS = 'MYADS',
  CONVERSATIONS = 'CONVERSATIONS',
  PROFILE = 'PROFILE',
  POSTAD = 'POSTAD',
  DUMMY = 'DUMMY',
  SUBCATEGORYLIST = 'SUBCATEGORYLIST',
  ADLIST = 'ADLIST',
  FULLADSCREEN = 'FULLADSCREEN',
  CHATSCREEN = 'CHATSCREEN',
  SUPPORT = 'SUPPORT',
  ROOTPROFILESCREEN = 'ROOTPROFILESCREEN',
  CREATEAD = 'CREATEAD',
  REPORTAD = 'REPORTAD',
  FAVORITEADS = 'FAVORITEADS',
  INAPPNOTIFICATIONS = 'INAPPNOTIFICATIONS',
  SHOWREPORTTEXRT = 'SHOWREPORTTEXRT',
  CONVERSATIONLIST = 'CONVERSATIONLIST',
}

export const adSubType = {
  PHONES: 'PHONES',

  HOUSE: 'HOUSE',
  LANDS: 'LANDS',
  SHOP: 'SHOP',
  PAYINGGUEST: 'PAYINGGUEST',

  CARS: 'CARS',
  BIKES: 'BIKES',
  VEHICLESSPAREPARTS: 'VEHICLESSPAREPARTS',

  ELECTRONICS: 'ELECTRONICS',
  ENTERTAINMENT: 'ENTERTAINMENT',
  KITCHENITEMS: 'KITCHENITEMS',
  COMPUTER: 'COMPUTER',
  GAMES: 'GAMES',
  HOUSEHOLD: 'HOUSEHOLD',
  OTHERELECTRONICS: 'OTHERELECTRONICS',
};

export const profileItemType = {
  NAME: 'NAME',
  SETTINGS: 'SETTINGS',
  NOTIFICATIONS: 'NOTIFICATIONS',
  RATEUS: 'RATEUS',
  VERSION: 'VERSION',
  SUPPORT: 'SUPPORT',
};

export const AsyncStorageKeys = {
  FCM_TOKEN: 'FCM_TOKEN',
};

export const postStatus = {
  ACTIVE: 'ACTIVE',
  SOLD: 'SOLD',
  DEACTIVATED: 'DE-ACTIVATED',
  EXPIRED: 'EXPIRED',
};
