name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}  # Use the branch selected in the UI

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Prepare Android environment
      run: sdkmanager --install "build-tools;33.0.2" "platforms;android-33" "ndk;26.1.10909125"

    - name: Build Android APK
      run: |
        cd android
        ./gradlew clean assembleRelease

    - name: Upload APK to AWS S3
      run: |
        aws s3 cp ./android/app/build/outputs/apk/release/app-release.apk s3://$AWS_BUCKET_NAME/releases/ --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
